/**
 * Legacy redirecty — mapování URL ze starých webů poboček na nové cesty.
 * Generováno z tabulek „URL (stávající adresy)" (Weby AHC). 301 v proxy.ts.
 */

const LEGACY_REDIRECTS: Record<string, Record<string, string>> = {
  "duchcov": {
    "/anesteziologie": "/oddeleni/anesteziologie",
    "/audio": "/",
    "/balicky-pro-pacienty": "/sluzby",
    "/benefity": "/kariera",
    "/caste-dotazy": "/",
    "/ceniky": "/sluzby",
    "/chirurgicka-ambulance": "/ambulance/chirurgicka-ambulance",
    "/chirurgicka-nasledna-pece": "/oddeleni/chirurgicka-nasledna-pece",
    "/chirurgicke-vysetreni": "/ambulance/chirurgicka-ambulance",
    "/desatero-komunikace": "/dokumenty",
    "/detska-neurologicka-ambulance": "/ambulance/detska-neurologicka-ambulance",
    "/diabetologicka-ambulance": "/ambulance/diabetologicka-ambulance",
    "/domaci-zdravotni-pece": "/oddeleni/domaci-zdravotni-pece",
    "/echokardiografie": "/ambulance/kardiologicka-ambulance",
    "/ekg": "/ambulance/kardiologicka-ambulance",
    "/ergometrie": "/ambulance/kardiologicka-ambulance",
    "/fibroskopie": "/ambulance/gastroenterologicka-ambulance",
    "/fyzioterapie": "/ambulance/fyzioterapie",
    "/gastroenterologicka-ambulance": "/ambulance/gastroenterologicka-ambulance",
    "/gdprmedvformulare": "/gdpr",
    "/gdprmedvp003-souhlas": "/gdpr",
    "/gdprmedvp004-komplex": "/gdpr",
    "/gdprvitaformulare": "/gdpr",
    "/gdprvitap001-partner": "/gdpr",
    "/gdprvitap002-marketing": "/gdpr",
    "/gdprvitap003-souhlas": "/gdpr",
    "/gdprvitap004-komplex": "/gdpr",
    "/gdprvitap005-pacienti": "/gdpr",
    "/gdprvitarozcestnik": "/gdpr",
    "/gynekologicka-ambulance": "/ambulance/gynekologicka-ambulance",
    "/gynekologicke-vysetreni": "/ambulance/gynekologicka-ambulance",
    "/historie-nemocnice": "/o-nas",
    "/holterovo-monitorovani-ekg": "/ambulance/kardiologicka-ambulance",
    "/interni-ambulance": "/ambulance/interni-ambulance",
    "/interni-nasledna-pece": "/oddeleni/interni-nasledna-pece",
    "/interni-vysetreni": "/ambulance/interni-ambulance",
    "/jednodenni-pece-luzkova": "/oddeleni/jednodenni-luzkova-pece",
    "/kardiologicka-ambulance": "/ambulance/kardiologicka-ambulance",
    "/kolonoskopie": "/ambulance/gastroenterologicka-ambulance",
    "/komplexni-kardiologicke-vysetreni": "/ambulance/kardiologicka-ambulance",
    "/koronavirus---pokyny": "/novinky",
    "/lekarna": "/sluzby",
    "/mapa-arealu": "/kontakt",
    "/mimoradna-provozni-doba": "/novinky",
    "/nase-oceneni": "/o-nas",
    "/nastaveni-cookies": "/gdpr",
    "/navstevy-luzkova-cast": "/oddeleni",
    "/o-nemocnici": "/o-nas",
    "/objednat-se": "/kontakt",
    "/ocni-ambulance": "/ambulance/ocni-ambulance",
    "/operace-stitne-zlazy": "/oddeleni/jednodenni-luzkova-pece",
    "/ortopedicka-ambulance": "/ambulance/ortopedicka-ambulance",
    "/osetrovatelska-nasledna-pece": "/oddeleni/osetrovatelska-nasledna-pece",
    "/parkovani-v-arealu-nemocnice": "/kontakt",
    "/pozice-skryte": "/kariera",
    "/prakticke-informace": "/sluzby",
    "/prava-a-povinnosti-pacienta": "/dokumenty",
    "/pravidla-pri-navsteve": "/ambulance",
    "/pravidla-pro-zajemce": "/oddeleni",
    "/predoperacni-vysetreni": "/ambulance/interni-ambulance",
    "/pro-pacienty": "/sluzby",
    "/rdg---radiodiagnosticke-oddeleni": "/oddeleni/rdg-radiodiagnosticke-oddeleni",
    "/sigmoideoskopie": "/ambulance/gastroenterologicka-ambulance",
    "/skryte": "/",
    "/smernice-pro-vyrizovani-stiznosti": "/dokumenty",
    "/urologicka-ambulance": "/ambulance/urologicka-ambulance",
    "/urologicke-vysetreni": "/ambulance/urologicka-ambulance",
    "/vedeni-nemocnice": "/o-nas",
    "/vysetreni-skryte": "/",
    "/zakaz-navstev": "/novinky",
    "/zdravotni-doprava": "/sluzby",
    "/zelena-firma": "/o-nas",
  },
  "kolin": {
    "/domaci-pece": "/sluzby",
    "/informace-o-cookies": "/gdpr",
    "/pro-zadatele": "/zadost-o-prijeti",
    "/senior-centrum": "/sluzby",
    "/spolupracujeme": "/",
    "/zasady-zpracovani-osobnich-udaju": "/gdpr",
  },
  "malacermna": {
    "/cenik": "/sluzby",
    "/domaci-pece": "/sluzby",
    "/informace-o-cookies": "/gdpr",
    "/nase-akce": "/novinky",
    "/nase-centrum": "/o-nas",
    "/postup-pro-prijeti-do-centra": "/zadost-o-prijeti",
    "/pro-zadatele": "/zadost-o-prijeti",
    "/spolupracujeme": "/",
    "/typ-sluzeb": "/sluzby",
    "/ubytovani-a-stravovani": "/sluzby",
    "/zakladni-informace": "/o-nas",
    "/zasady-zpracovani-osobnich-udaju": "/gdpr",
  },
  "mezibori": {
    "/domaci-pece": "/sluzby",
    "/informace-o-cookies": "/gdpr",
    "/jak-se-stat-nasim-klientem": "/zadost-o-prijeti",
    "/nase-centrum": "/o-nas",
    "/pro-zadatele": "/sluzby",
    "/zasady-zpracovani-osobnich-udaju": "/gdpr",
  },
  "novarole": {
    "/akce---aktuality": "/novinky",
    "/domaci-pece": "/sluzby",
    "/eticky-kodex": "/dokumenty",
    "/formulare": "/dokumenty",
    "/informace": "/novinky",
    "/informace-o-cookies": "/gdpr",
    "/o-ahc": "/o-nas",
    "/pro-zadatele": "/zadost-o-prijeti",
    "/skryte": "/",
    "/typ-sluzeb": "/sluzby",
    "/zasady-zpracovani-osobnich-udaju": "/gdpr",
  },
  "novestraseci": {
    "/aktivizace-a-fyzioterapie": "/sluzby",
    "/cenik": "/sluzby",
    "/darci": "/",
    "/informace-o-cookies": "/gdpr",
    "/o-domove": "/o-nas",
    "/rodina": "/sluzby",
    "/skryte": "/",
    "/stravovani": "/sluzby",
    "/tym": "/o-nas",
    "/ubytovani": "/sluzby",
    "/vyrocni-zpravy": "/dokumenty",
    "/zasady-zpracovani-osobnich-udaju": "/gdpr",
    "/zdravotni-pece": "/sluzby",
  },
  "novybor": {
    "/dokumenty-ke-stazeni---pece": "/dokumenty",
    "/domaci-pece": "/sluzby",
    "/domov-pro-seniory": "/sluzby",
    "/doplnkove-sluzby": "/sluzby",
    "/informace-o-cookies": "/gdpr",
    "/informace-pro-zajemce---pece": "/zadost-o-prijeti",
    "/nasledna-pece": "/sluzby",
    "/podminky-prijeti": "/zadost-o-prijeti",
    "/podminky-prijeti---pece": "/zadost-o-prijeti",
    "/poskytovane-sluzby---pece": "/sluzby",
    "/zasady-zpracovani-osobnich-udaju": "/gdpr",
  },
  "pecicky": {
    "/domov-se--zvlastnim-rezimem": "/sluzby",
    "/informace-o-cookies": "/gdpr",
    "/partneri": "/",
    "/skryte": "/",
    "/zasady-zpracovani-osobnich-udaju": "/gdpr",
  },
  "prepychy": {
    "/cenik": "/sluzby",
    "/domaci-pece": "/sluzby",
    "/informace-o-cookies": "/gdpr",
    "/nase-akce": "/novinky",
    "/nase-centrum": "/o-nas",
    "/postup-pro-prijeti-do-centra": "/zadost-o-prijeti",
    "/pro-zadatele": "/zadost-o-prijeti",
    "/spolupracujeme": "/",
    "/typ-sluzeb": "/sluzby",
    "/ubytovani-a-stravovani": "/sluzby",
    "/zakladni-informace": "/o-nas",
    "/zasady-zpracovani-osobnich-udaju": "/gdpr",
  },
  "pribram": {
    "/akce---aktuality": "/novinky",
    "/aktivity-klientu": "/o-nas",
    "/certifikaty-a-oceneni": "/o-nas",
    "/domaci-pece": "/sluzby",
    "/foto-z-akci-2013": "/o-nas",
    "/foto-z-akci-2014": "/o-nas",
    "/foto-z-akci-2015": "/o-nas",
    "/foto-z-akci-2016": "/o-nas",
    "/informace-o-cookies": "/gdpr",
    "/kontaktni-misto-cals": "/sluzby",
    "/nase-centrum": "/o-nas",
    "/postup-prijeti-do-centra": "/zadost-o-prijeti",
    "/pro-zadatele": "/zadost-o-prijeti",
    "/spolupracujeme": "/",
    "/svepomocna-skupina": "/sluzby",
    "/typ-sluzeb": "/sluzby",
    "/vysetreni-pameti": "/sluzby",
    "/zakladni-informace": "/o-nas",
    "/zasady-zpracovani-osobnich-udaju": "/gdpr",
  },
  "rehabilitacnicentrummezibori": {
    "/book-online": "/zadost-o-prijeti",
    "/faq": "/",
    "/kristyna-cerna": "/o-nas",
    "/lenkapalmova": "/o-nas",
    "/michaelacernohorska": "/o-nas",
    "/my-addresses": "/",
    "/nasesluzby": "/sluzby",
    "/nastym": "/o-nas",
    "/onas": "/o-nas",
    "/radkabalazova": "/o-nas",
  },
  "sedlec-prcice": {
    "/dokumenty-ke-stazeni---pece": "/dokumenty",
    "/domaci-pece": "/sluzby",
    "/domov-pro-seniory": "/sluzby",
    "/doplnkove-sluzby": "/sluzby",
    "/informace-o-cookies": "/gdpr",
    "/informace-pro-zajemce---pece": "/zadost-o-prijeti",
    "/nasledna-pece": "/sluzby",
    "/podminky-prijeti": "/zadost-o-prijeti",
    "/podminky-prijeti---pece": "/zadost-o-prijeti",
    "/poskytovane-sluzby---pece": "/sluzby",
    "/zasady-zpracovani-osobnich-udaju": "/gdpr",
  },
  "stribro": {
    "/brezen-2024---ocista-a-novy-dech-pro-misto-kde-vznika-domov": "/novinky",
    "/brezen-2025---prvni-barvy-domova": "/novinky",
    "/cerven-2024---stavime-pevne-myslime-do-detailu": "/novinky",
    "/cerven-2025---dokoncovaci-prace": "/novinky",
    "/cervenec-2024---teplo-sucho-a-pohodli--od-zakladu-po-strechu": "/novinky",
    "/cervenec-2025---slavnostni-otevreni": "/novinky",
    "/dotazy": "/sluzby",
    "/duben-2024---zpevnujeme-zaklady-budouci-jistoty": "/novinky",
    "/duben-2025---domov-dostava-dusi": "/novinky",
    "/informace-o-cookies": "/gdpr",
    "/jak-centrum-roste": "/novinky",
    "/kveten-2024---pevna-puda-pod-nohama": "/novinky",
    "/kveten-2025---mame-zkolaudovano": "/novinky",
    "/leden-2024---projekt-ktery-pomuze-desitkam-senioru": "/novinky",
    "/leden-2025---v-srdci-budouciho-domova": "/novinky",
    "/listopad-2024---kdyz-domov-dostane-tvar": "/novinky",
    "/lokalita": "/o-nas",
    "/o-senior-centru": "/o-nas",
    "/rijen-2024---hrejivy-vnitrek-pohledna-tvar-zvenci": "/novinky",
    "/skryte": "/",
    "/skryte-2": "/",
    "/srpen-2024---srdce-domu-oziva": "/novinky",
    "/unor-2024---bourame-abychom-mohli-tvorit": "/novinky",
    "/zari-2024---svetlo-teplo-a-blizici-se-utulno": "/novinky",
    "/zasady-zpracovani-osobnich-udaju": "/gdpr",
  },
  "trutnov": {
    "/babybox": "/sluzby",
    "/cenik": "/sluzby",
    "/domaci-pece": "/sluzby",
    "/eticky-kodex---stiznosti": "/dokumenty",
    "/informace-o-cookies": "/gdpr",
    "/nase-sanatorium": "/o-nas",
    "/podekovani": "/o-nas",
    "/socialni-pece": "/sluzby",
    "/spolupracujeme": "/",
    "/zasady-zpracovani-osobnich-udaju": "/gdpr",
    "/zdravotni-pece": "/sluzby",
  },
  "vizovice": {
    "/bavsen": "/novinky",
    "/darci-a-sponzori": "/",
    "/dokumenty-ke-stazeni-os": "/dokumenty",
    "/dokumenty-ke-stazeni-ps": "/dokumenty",
    "/dokumenty-ke-stazeni-tos": "/dokumenty",
    "/foto": "/o-nas",
    "/informace-o-cookies": "/gdpr",
    "/koncepty-pece": "/sluzby",
    "/material-k-aktivizaci---csob": "/novinky",
    "/nakup-kompenzacnich-pomucek---ep-corporate-group": "/novinky",
    "/novy-automobil": "/novinky",
    "/novy-automobil-pro-ahc-odlehcovaci-centrum-vizovice-zu": "/novinky",
    "/odlehcovaci-sluzba": "/sluzby",
    "/odlehcovaci-sluzba1": "/sluzby",
    "/pecovatelska-sluzba": "/sluzby",
    "/pecovatelska-sluzba1": "/sluzby",
    "/pedikura": "/sluzby",
    "/priklady-z-praxe": "/sluzby",
    "/projekty": "/novinky",
    "/pujcovna-kompenzacnich-pomucek": "/sluzby",
    "/spolecnost": "/o-nas",
    "/susicka-pradla-pro-ahc-vizovice": "/novinky",
    "/take-jsem-byla-mladya": "/novinky",
    "/terenni-odlehcovaci-sluzba": "/sluzby",
    "/terenni-odlehcovaci-sluzba1": "/sluzby",
    "/vyrocni-zpravy": "/dokumenty",
    "/vzdelavame-se-pro-klienty-2023---nadace-cez": "/novinky",
    "/vzdelavame-se-pro-klienty-20232024": "/novinky",
    "/zakladni-cinnosti-os": "/sluzby",
    "/zakladni-cinnosti-ps": "/sluzby",
    "/zasady-zpracovani-osobnich-udaju": "/gdpr",
    "/zimni-zahrada-a-zahrada-smyslu": "/o-nas",
    "/zvireci-navstevy": "/novinky",
  },
};

export function getLegacyRedirect(
  branchSlug: string | null,
  path: string
): string | null {
  if (!branchSlug) return null;
  const map = LEGACY_REDIRECTS[branchSlug];
  if (!map) return null;
  const normalized = path.length > 1 ? path.replace(/\/+$/, "") : path;
  return map[normalized] ?? null;
}
